site_name: cookiecutter tox plugin
site_description: Minimal Cookiecutter template for authoring tox plugins.
site_author: Oliver Bestwalter

theme: readthedocs

repo_url: https://github.com/tox-dev/cookiecutter-tox-plugin

pages:
- Home: index.md
- User Guide:
    - Quickstart: user-guide/quickstart.md
    - Publish: user-guide/publish-plugin.md
- Contributor Guide:
    - Quickstart: contributor-guide/quickstart.md
    - Documentation: contributor-guide/documentation.md
